language: go
go:
  - 1.4
  - 1.5
  - 1.6
  - 1.7
  - tip
notificaitons:
  email:
    recipients:
      robert@nicerobot.org
    on_success: change
    on_failure: always
install:
  - go get -t ./...
script:
  - go test -v
